GRANT ALL PRIVILEGES ON *.* TO 'db_user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES; -- run to apply changes

CREATE DATABASE IF NOT EXISTS test_optimo_mysql_db;
GRANT ALL PRIVILEGES ON test_optimo_mysql_db.* TO 'db_user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

USE optimo_mysql_db;

CREATE TABLE IF NOT EXISTS flask_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    level VARCHAR(10) NOT NULL,
    message TEXT NOT NULL
);
FLUSH PRIVILEGES;
